ResearchCollectionsAndPreservation/scsb-ui

src/main/resources/application-dev.properties, src/main/resources/application-local-container.properties, src/main/resources/application-tst.properties, src/main/resources/application-uat.properties
=> updated the mysql url

src/main/java/org/recap/controller/ReportsController.java, src/main/java/org/recap/model/jpa/RequestItemEntity.java, src/main/java/org/recap/model/search/ReportsForm.java, src/main/java/org/recap/repository/jpa/ItemChangeLogDetailsRepository.java, src/main/java/org/recap/util/ReportsUtil.java, src/main/resources/static/js/report.js, src/main/resources/templates/reports.html, src/test/java/org/recap/controller/ReportsControllerUT.java, src/test/java/org/recap/repository/jpa/ItemChangeLogDetailsRepositoryUT.java, src/test/java/org/recap/repository/jpa/RequestItemDetailsRepositoryUT.java
=> Added Reports UI - RECAP 322

src/main/java/org/recap/RecapConstants.java, src/main/java/org/recap/controller/LoginController.java, src/main/resources/application-local-container.properties, src/main/resources/application-uat.properties, src/main/resources/static/js/main.js, src/main/resources/templates/recapHeader.html
SCSB-UI Authentication changes & code clean up
=> SCSB-UI Authentication changes & code clean up

src/main/java/org/recap/Main.java, src/main/java/org/recap/controller/CollectionController.java, src/main/java/org/recap/controller/LoginController.java, src/main/java/org/recap/controller/ReportsController.java, src/main/java/org/recap/controller/RequestController.java, src/main/java/org/recap/controller/SearchRecordsController.java, src/main/java/org/recap/security/SessionFilter.java, src/main/java/org/recap/security/UserManagement.java, src/main/java/org/recap/util/UserAuthUtil.java, src/main/resources/application-dev.properties, src/main/resources/application-local-container.properties, src/main/resources/application-local.properties, src/main/resources/application-tst.properties, src/main/resources/application-uat.properties
Session Time confir and login screen redirection
=> Session Time confir and login screen redirection

src/main/resources/application-local.properties
Session time value changed to 15 minutes
=> Session time value changed to 15 minutes

src/main/java/org/recap/controller/RolesController.java, src/main/java/org/recap/model/search/RolesForm.java, src/main/java/org/recap/model/search/RolesSearchResult.java, src/main/java/org/recap/repository/jpa/PermissionsDetailsRepository.java, src/main/resources/static/css/roles.css, src/main/resources/static/js/bootstrap-add-clear.min.js, src/main/resources/static/js/roles.js, src/main/resources/templates/roles.html, src/test/java/org/recap/controller/RolesControllerUT.java, src/test/java/org/recap/repository/jpa/RolesDetailsRepositortyUT.java
Recap-350 and 359 Roles and
updated icons for roles and users tab.
=> Recap-320 clear X icon in search tab fixed,

src/main/java/org/recap/controller/UserRoleController.java, src/main/java/org/recap/model/jpa/UsersEntity.java, src/main/java/org/recap/model/userManagement/UserRoleForm.java, src/main/java/org/recap/model/userManagement/UserRoleService.java, src/main/java/org/recap/model/userManagement/UserRoleServiceImpl.java, src/main/java/org/recap/model/userManagement/UserRoleValidator.java, src/main/java/org/recap/model/userManagement/UserSearchResultRow.java, src/main/java/org/recap/repository/jpa/RolesDetailsRepositorty.java, src/main/java/org/recap/repository/jpa/UserDetailsRepository.java, src/main/resources/static/js/userRole.js, src/main/resources/templates/searchRecords.html, src/main/resources/templates/userRolesSearch.html
=> ReCAP-351 Users Screen

build.gradle, src/main/java/org/recap/RecapConstants.java, src/main/java/org/recap/controller/LoginController.java, src/main/java/org/recap/controller/RequestController.java, src/main/java/org/recap/controller/RolesController.java, src/main/java/org/recap/controller/UserRoleController.java, src/main/resources/templates/searchRecords.html
Permissions added to Roles & Users tab
=> Permissions added to Roles & Users tab

src/main/java/org/recap/Main.java, src/main/java/org/recap/controller/CollectionController.java, src/main/java/org/recap/controller/RequestController.java, src/main/java/org/recap/controller/UserRoleController.java, src/main/java/org/recap/util/UserAuthUtil.java
User Tab permission impl & code refractor
=> User Tab permission impl & code refractor

src/main/java/org/recap/RecapConstants.java, src/main/java/org/recap/controller/RolesController.java, src/main/java/org/recap/model/search/RolesForm.java, src/main/java/org/recap/model/userManagement/UserRoleForm.java, src/main/java/org/recap/model/userManagement/UserRoleService.java, src/main/java/org/recap/model/userManagement/UserRoleServiceImpl.java, src/main/java/org/recap/repository/jpa/RolesDetailsRepositorty.java, src/main/java/org/recap/repository/jpa/UserDetailsRepository.java, src/main/resources/static/js/roles.js, src/main/resources/static/js/userRole.js, src/main/resources/templates/roles.html, src/main/resources/templates/userRolesSearch.html, src/test/java/org/recap/controller/ReportsControllerUT.java, src/test/java/org/recap/controller/RolesControllerUT.java
=> ui issues fixed in roles 

src/main/java/org/recap/controller/RolesController.java, src/main/java/org/recap/controller/UserRoleController.java, src/main/java/org/recap/model/search/RolesForm.java, src/main/java/org/recap/model/userManagement/UserRoleForm.java, src/main/java/org/recap/model/userManagement/UserRoleServiceImpl.java, src/main/resources/static/css/styles.css, src/main/resources/static/js/roles.js, src/main/resources/static/js/userRole.js, src/main/resources/templates/roles.html, src/main/resources/templates/userRolesSearch.html
Changed Delete Screen in User Screen(ReCAP-351) and Roles Screen.
=> Changed Delete Screen in User Screen(ReCAP-351) and Roles Screen.

src/main/java/org/recap/controller/UserRoleController.java, src/main/java/org/recap/model/userManagement/UserRoleForm.java, src/main/java/org/recap/model/userManagement/UserRoleServiceImpl.java, src/main/resources/static/css/styles.css, src/main/resources/static/js/userRole.js, src/main/resources/templates/roles.html, src/main/resources/templates/userRolesSearch.html
Changed CSS For UserScreen and Roles Screen
=> Changed CSS For UserScreen and Roles Screen

src/main/java/org/recap/controller/RequestController.java, src/main/resources/application-dev.properties, src/main/resources/application-local-container.properties, src/main/resources/application-local.properties, src/main/resources/application-tst.properties, src/main/resources/application-uat.properties
Session Time out changed to 30 minutes & Delivery location will be listed based on logged in user institution.
=> Session Time out & Delivery location changes

src/main/java/org/recap/RecapConstants.java, src/main/java/org/recap/controller/UserRoleController.java, src/main/java/org/recap/model/userManagement/UserRoleForm.java, src/main/java/org/recap/model/userManagement/UserRoleServiceImpl.java, src/main/resources/static/js/userRole.js, src/main/resources/templates/userRolesSearch.html
RECAP-351 Added Recap constants and Changed CSS for User Screen
=> RECAP-351 Added Recap constants and Changed CSS for User Screen

src/main/resources/templates/search.html
=> Code clean up

src/main/java/org/recap/controller/UserRoleController.java, src/main/java/org/recap/model/userManagement/UserRoleServiceImpl.java, src/main/resources/static/js/roles.js, src/main/resources/static/js/userRole.js, src/main/resources/templates/roles.html, src/main/resources/templates/userRolesSearch.html
ReCAP 351 - Removed Mandatory Field and Validations For For emailId
=> ReCAP 351 - Removed Mandatory Field and Validations For For emailId

src/main/resources/static/js/main.js, src/main/resources/templates/userRolesSearch.html
Recap-351 Resolved viewport height and changed Font color in User Screen.
=> Recap-351 Resolved viewport height and changed Font color in User Screen.

src/main/java/org/recap/controller/CollectionController.java, src/main/java/org/recap/controller/LoginController.java, src/main/java/org/recap/controller/ReportsController.java, src/main/java/org/recap/controller/RequestController.java, src/main/java/org/recap/controller/RolesController.java, src/main/java/org/recap/controller/SearchRecordsController.java, src/main/java/org/recap/controller/UserRoleController.java, src/main/java/org/recap/model/userManagement/UserForm.java, src/main/java/org/recap/security/UserManagement.java, src/main/java/org/recap/util/UserAuthUtil.java
Handiling exception scenarios and Unauthorized user handling
=> Handiling exception scenarios and Unauthorized user handling

src/main/java/org/recap/controller/RequestController.java, src/main/java/org/recap/model/search/SearchResultRow.java
Recap-425 fixed request ui redirecting to login page  when search button clicked
=> Recap-425 fixed request ui redirecting to login page when search button clicked

src/main/java/org/recap/controller/RolesController.java
Recap-350 UsersEntity attribute added to Edit Roles in Roles Screen.
=> Recap-350 UsersEntity attribute added to Edit Roles in Roles Screen.

src/main/java/org/recap/controller/RolesController.java, src/main/java/org/recap/controller/UserRoleController.java, src/main/java/org/recap/model/jpa/RoleEntity.java, src/main/java/org/recap/model/jpa/UsersEntity.java, src/main/java/org/recap/model/userManagement/UserRoleForm.java, src/main/java/org/recap/model/userManagement/UserRoleService.java, src/main/java/org/recap/model/userManagement/UserRoleServiceImpl.java, src/main/java/org/recap/security/UserManagement.java, src/main/resources/templates/roles.html, src/test/java/org/recap/controller/RolesControllerUT.java, src/test/java/org/recap/controller/UserRoleControllerUT.java, src/test/java/org/recap/model/usermanagement/UserRoleServiceImplUT.java, src/test/java/org/recap/repository/jpa/RolesDetailsRepositortyUT.java, src/test/java/org/recap/repository/jpa/UserDetailsRepositoryUT.java
Recap-419 added CreatedDate , CreatedBy,LastUpdatedDate,LastUpdatedBy in RoleEntity and UsersEntity.
=> Recap-419 added CreatedDate , CreatedBy,LastUpdatedDate,LastUpdatedBy in RoleEntity and UsersEntity

src/main/java/org/recap/controller/RequestController.java
try catch block added in request Controller
=> try catch block added in request Controller

build.gradle
Added jacoco plugin for testcase coverage
=> Added jacoco plugin for testcase coverage

src/main/resources/application-dev.properties, src/main/resources/application-junit.properties, src/main/resources/application-local-container.properties, src/main/resources/application-local.properties, src/main/resources/application-tst.properties, src/main/resources/application-uat.properties
=> Added junit property

src/main/resources/static/js/userRole.js, src/main/resources/templates/userRolesSearch.html
Recap-351-(users Screen)When hitting the Enter key inside input textbox should display the results
=> Recap-351-(users Screen)When hitting the Enter key inside input textbox should display the results

src/main/resources/static/js/userRole.js, src/main/resources/templates/userRolesSearch.html
Added email validation in Create and Edit User Screen
=> Added email validation in Create and Edit User Screen

src/main/resources/static/css/request.css, src/main/resources/static/js/request.js, src/main/resources/templates/request.html
REC-159 flickering issue in request UI fixed
=> REC-159 flickering issue in request UI fixed

src/main/java/org/recap/util/ReportsUtil.java, src/main/resources/static/js/report.js
Recap-450 & Recap-451 - Fixed Count mismatch in Deaccession Link
=> Recap-450 & Recap-451 - Fixed Count mismatch in Deaccession Link

src/main/java/org/recap/repository/jpa/HoldingsDetailsRepository.java, src/main/java/org/recap/repository/jpa/PermissionsDetailsRepository.java, src/test/java/org/recap/BaseTestCase.java, src/test/java/org/recap/repository/jpa/HoldingsDetailsRepositoryUT.java, src/test/java/org/recap/repository/jpa/PatronRepositoryUT.java, src/test/java/org/recap/repository/jpa/PermissionsDetailsRepositoryUT.java, src/test/java/org/recap/repository/jpa/ReportDetailRepositoryUT.java, src/test/java/org/recap/repository/jpa/RequestTypeDetailsRepositoryUT.java, src/test/java/org/recap/repository/jpa/UserDetailsRepositoryUT.java, src/test/java/org/recap/util/UserAuthUtilUT.java
=> Changes for JUnit test

src/main/resources/static/css/styles.css, src/main/resources/templates/userRolesSearch.html
Recap-479-Added Tooltip in dropdown list
=> Recap-479-Added Tooltip in dropdown list

src/test/java/org/recap/controller/ReportsControllerUT.java
Report Controller UT Issue Fixing
=> Report Controller UT Issue Fixing

src/main/java/org/recap/controller/ReportsController.java, src/main/java/org/recap/controller/RequestController.java, src/main/java/org/recap/controller/SearchRecordsController.java, src/main/resources/static/js/report.js, src/main/resources/static/js/search.js, src/main/resources/templates/recapFooter.html, src/main/resources/templates/recapHeader.html, src/main/resources/templates/reports.html, src/main/resources/templates/search.html, src/test/java/org/recap/controller/SearchRecordsControllerUT.java
Recap-424 scsb ui changes in recap header, recap footer,reports ui ,enabled request button in search ui.
=> Recap-424 scsb ui changes in recap header, recap footer,reports ui ,enabled request button in search ui.

src/main/java/org/recap/controller/RolesController.java, src/main/java/org/recap/model/search/RolesForm.java, src/main/resources/static/js/roles.js, src/main/resources/templates/roles.html
escape sequence in role search results fixed , flickering issue in roles fixed
=> escape sequence in role search results fixed , flickering issue in roles fixed

src/main/java/org/recap/RecapConstants.java, src/main/java/org/recap/controller/UserRoleController.java, src/main/java/org/recap/model/userManagement/UserRoleForm.java, src/main/java/org/recap/model/userManagement/UserRoleServiceImpl.java, src/main/resources/static/js/collection.js, src/main/resources/static/js/report.js, src/main/resources/static/js/request.js, src/main/resources/static/js/roles.js, src/main/resources/static/js/userRole.js, src/main/resources/templates/recapHeader.html, src/main/resources/templates/request.html, src/main/resources/templates/userRolesSearch.html
added help links , resolved edit users and delete users with same loginId and different institutions
=> added help links , resolved edit users and delete users with same loginId and different institutions

src/main/java/org/recap/RecapConstants.java, src/main/java/org/recap/controller/RequestController.java, src/main/java/org/recap/controller/SearchRecordsController.java, src/main/resources/static/js/request.js, src/main/resources/templates/request.html
Recap-493 populating item title and institution in request Ui.
=> Recap-493 populating item title and institution in request Ui.

src/main/java/org/recap/RecapConstants.java, src/main/java/org/recap/repository/jpa/RequestItemDetailsRepository.java, src/main/java/org/recap/util/RequestServiceUtil.java, src/main/resources/static/js/request.js, src/main/resources/templates/reports.html, src/main/resources/templates/request.html
Recap-501 redefined search conditions for request search
=> Recap-501 redefined search conditions for request search

src/main/resources/application-tst.properties
Update the tst properties with https
=> Update the tst properties with https

src/main/resources/application-tst.properties
Modified for RECAP-491 : Removed port for tst.
=> Modified for RECAP-491 : Removed port for tst.

src/main/resources/application-tst.properties
Modified for RECAP-491 : Modified property to connect HTC Cas
=> Modified for RECAP-491 : Modified property to connect HTC Cas

src/main/java/org/recap/controller/RequestController.java, src/main/resources/static/css/request.css, src/main/resources/static/js/request.js, src/main/resources/templates/collection.html, src/main/resources/templates/reports.html, src/main/resources/templates/request.html
=> Request flickering resolved

src/main/java/org/recap/Main.java, src/main/java/org/recap/filter/ReCAPInstitutionFilter.java, src/main/java/org/recap/security/ReCAPExceptionTranslationFilter.java, src/main/java/org/recap/util/HelperUtil.java, src/main/resources/application-dev.properties, src/main/resources/application-junit.properties, src/main/resources/application-local-container.properties, src/main/resources/application-local.properties, src/main/resources/application-tst.properties, src/main/resources/application-uat.properties
RECAP-491 : Fixed issue with navigation after authentication.
=> RECAP-491 : Fixed issue with navigation after authentication.

src/main/java/org/recap/controller/RolesController.java, src/main/java/org/recap/controller/UserRoleController.java, src/main/resources/static/js/roles.js, src/main/resources/static/js/userRole.js
Recap-516 fixed edit and delete user roles
=> Recap-516 fixed edit and delete user roles

src/main/java/org/recap/repository/jpa/RequestItemDetailsRepository.java
ReCap-528 fixed bound-with search issues in request ui
=> ReCap-528 fixed bound-with search issues in request ui

src/main/java/org/recap/RecapConstants.java, src/main/java/org/recap/controller/LoginController.java, src/main/java/org/recap/security/ReCAPSimpleUrlLogoutSuccessHandler.java
RECAP-544 : Restricted the login screen after successful login.
=> RECAP-544 : Restricted the login screen after successful login.

src/main/java/org/recap/util/ReportsUtil.java, src/main/resources/static/js/report.js, src/main/resources/templates/reports.html, src/main/resources/templates/roles.html, src/main/resources/templates/userRolesSearch.html
Recap-523 ui changes for reports,roles and users tab
=> Recap-523 ui changes for reports,roles and users tab

src/main/java/org/recap/RecapConstants.java, src/main/java/org/recap/controller/RolesController.java, src/main/java/org/recap/controller/UserRoleController.java, src/main/java/org/recap/model/userManagement/UserRoleServiceImpl.java
Recap-530 Modified RecapConstant terms
=> Recap-530 Modified RecapConstant terms

src/main/java/org/recap/RecapConstants.java, src/main/java/org/recap/controller/ReportsController.java, src/main/java/org/recap/model/reports/ReportsRequest.java, src/main/java/org/recap/model/reports/ReportsResponse.java, src/main/java/org/recap/model/search/IncompleteReportResultsRow.java, src/main/java/org/recap/model/search/ReportsForm.java, src/main/java/org/recap/repository/jpa/InstitutionDetailsRepository.java, src/main/java/org/recap/util/ReportsServiceUtil.java, src/main/java/org/recap/util/ReportsUtil.java, src/main/resources/static/js/report.js, src/main/resources/templates/reports.html, src/test/java/org/recap/controller/ReportsControllerUT.java, src/test/java/org/recap/util/ReportsUtilUT.java
Recap-552 Incomplete Record Report For accession
=> Recap-552 Incomplete Record Report For accession

src/main/resources/static/js/request.js, src/main/resources/templates/request.html
Recap 576 EDD Request needs to have a mandatory email address .
=> Recap 576 EDD Request needs to have a mandatory email address .

src/main/java/org/recap/controller/ReportsController.java
filter removed for institutions in incomplete Report.
=> filter removed for institutions in incomplete Report.

src/main/resources/templates/recapFooter.html
=> Fixed Version Number Issue

src/main/java/org/recap/security/ReCAPSimpleUrlLogoutSuccessHandler.java, src/main/resources/static/js/login.js, src/main/resources/templates/login.html
RECAP-585 : Modified to logout user if user not available in SCSB.
=> RECAP-585 : Modified to logout user if user not available in SCSB.

src/main/java/org/recap/controller/SearchRecordsController.java
Fixed Issue to display error message when Barcode in not found
=> Fixed Issue to display error message when Barcode in not found

src/main/resources/application-uat.properties
Updated the UAT property file.
=> Updated the UAT property file.

src/main/java/org/recap/controller/ReportsController.java, src/main/java/org/recap/controller/UserRoleController.java, src/main/java/org/recap/model/usermanagement/UserRoleForm.java, src/main/java/org/recap/model/usermanagement/UserRoleServiceImpl.java, src/main/java/org/recap/repository/jpa/UserDetailsRepository.java, src/main/resources/static/js/report.js, src/main/resources/templates/searchRecords.html, src/main/resources/templates/userRolesSearch.html, src/test/java/org/recap/repository/jpa/UserDetailsRepositoryUT.java
Recap-606 fixed pagination in incomplete report and Recap-609 Logged in user shown in user search results.
=> Recap-606 fixed pagination in incomplete report and Recap-609 Logged in user shown in user search results.

src/main/resources/templates/reports.html
Recap-611 In Report tab, Add From and To labels over each calendar under Date Range.
=> Recap-611 In Report tab, Add From and To labels over each calendar under Date Range.

src/main/resources/templates/collection.html
fixed edit cgd  notes margin issue
=> fixed edit cgd  notes margin issue

src/main/java/org/recap/controller/RequestController.java, src/main/java/org/recap/model/jpa/CustomerCodeEntity.java, src/main/java/org/recap/model/jpa/DeliveryRestrictionEntity.java, src/main/java/org/recap/model/search/RequestForm.java, src/main/resources/static/js/request.js, src/main/resources/templates/request.html, src/main/resources/templates/userRolesSearch.html
Recap-618 - Request- Populate delivery locations based on item barcode and requesting institution
=> Recap-618 - Request- Populate delivery locations based on item barcode and requesting institution

src/main/java/org/recap/model/search/DeaccessionItemResultsRow.java, src/main/resources/templates/reports.html
Recap-617 Deaccession report not working for Columbia.
=> Recap-617 Deaccession report not working for Columbia.

src/main/java/org/recap/RecapConstants.java, src/main/java/org/recap/controller/RequestController.java, src/main/java/org/recap/controller/SearchRecordsController.java, src/main/java/org/recap/repository/jpa/RequestTypeDetailsRepository.java
Recap-597 Out items should not be requestable via the button
=> Recap-597 Out items should not be requestable via the button

src/main/resources/static/js/request.js, src/main/resources/static/js/roles.js, src/main/resources/static/js/userRole.js, src/main/resources/templates/collection.html, src/main/resources/templates/request.html, src/main/resources/templates/roles.html, src/main/resources/templates/userRolesSearch.html
Client side validation to alert on exceeding DB field length
=> Recap-629 Client side validation to alert on exceeding DB field length.

src/main/resources/static/js/request.js, src/main/resources/templates/roles.html, src/main/resources/templates/userRolesSearch.html
Changed alignment for edit button in roles and user screen, Changed the success message symbol to tick mark
=> Recap-637 - UI changes

src/main/resources/static/js/collection.js, src/main/resources/static/js/report.js, src/main/resources/templates/collection.html, src/main/resources/templates/reports.html
Recap-635 UX feedback - Reports.
=> Recap-635 UX feedback - Reports.

src/main/resources/static/css/styles.css, src/main/resources/static/js/report.js, src/main/resources/templates/reports.html
Recap-635 UX feedback - Reports - Tab Key Navigation.
=> Recap-635 UX feedback - Reports - Tab Key Navigation.

src/main/java/org/recap/controller/ReportsController.java
Recap-648 An EDD request was submitted , but it’s not showing up in the Reports.
=> Recap-648 An EDD request was submitted , but it’s not showing up in the Reports.

src/main/java/org/recap/controller/RequestController.java, src/main/java/org/recap/model/jpa/CustomerCodeEntity.java
logic added to populate recap delivery restrictions only for recap users.
=> logic added to populate recap delivery restrictions only for recap users.

src/main/java/org/recap/controller/RequestController.java, src/main/java/org/recap/controller/RolesController.java, src/main/java/org/recap/controller/UserRoleController.java, src/main/java/org/recap/model/search/RequestForm.java, src/main/java/org/recap/repository/jpa/RequestItemDetailsRepository.java, src/main/java/org/recap/util/RequestServiceUtil.java, src/main/resources/static/css/styles.css, src/main/resources/static/js/request.js, src/main/resources/static/js/roles.js, src/main/resources/static/js/userRole.js, src/main/resources/templates/request.html, src/main/resources/templates/roles.html, src/main/resources/templates/userRolesSearch.html
=> Recap-615,634 UI changes

src/test/java/org/recap/controller/RequestControllerUT.java, src/test/java/org/recap/controller/UserRoleControllerUT.java
Fixed TestCase for RequestControllerUT and UserRoleControllerUT
=> Fixed TestCase for RequestControllerUT and UserRoleControllerUT

src/main/resources/static/css/styles.css, src/main/resources/static/js/request.js
Recap-615 Request Submitted screen with textboxes
=> Recap-615 Request Submitted screen with textboxes

src/main/resources/templates/request.html
Fixed Issue for Placing requests for own institution's items and Shared/Open items of other institution
=> Fixed Issue for Placing requests for own institution's items and Shared/Open items of other institution

src/main/resources/static/js/request.js, src/main/resources/templates/reports.html
Fixed issues- Alignment in Reports and Corrected Spelling mistake for canceled
=> Fixed issues- Alignment in Reports and Corrected Spelling mistake for canceled

src/main/java/org/recap/controller/RequestController.java, src/main/java/org/recap/controller/UserRoleController.java, src/main/java/org/recap/model/search/RequestForm.java, src/main/resources/static/js/request.js, src/main/resources/static/js/userRole.js, src/main/resources/templates/request.html, src/main/resources/templates/userRolesSearch.html
=> Recap 634 and 637 UI Changes

src/main/resources/static/js/collection.js, src/main/resources/static/js/request.js, src/main/resources/static/js/roles.js, src/main/resources/static/js/userRole.js, src/main/resources/templates/collection.html, src/main/resources/templates/request.html, src/main/resources/templates/roles.html, src/main/resources/templates/userRolesSearch.html
Added Js for displaying Number of characters Remaining for all Length Validating fields
=> Added Js for displaying Number of characters Remaining for all Length Validating fields

src/main/resources/static/js/collection.js, src/main/resources/static/js/request.js, src/main/resources/templates/collection.html, src/main/resources/templates/request.html
Fixed Bug for hiding the Remaining characters after submitting in Collection Screen and Request Screen
=> Fixed Bug for hiding the Remaining characters after submitting in Collection Screen and Request Screen

src/main/java/org/recap/RecapConstants.java, src/test/java/org/recap/controller/RequestControllerUT.java
Recap-693 Edited the error Message
=> Recap-693 Edited the error Message

src/main/java/org/recap/Main.java, src/main/java/org/recap/security/ReCAPExceptionTranslationFilter.java
RECAP-605 : Handled session time out.
=> RECAP-605 : Handled session timedout.

src/main/resources/static/js/request.js
Recap701 - Fixed Bug (To dispay EDD details after submitting)
=> Recap701 - Fixed Bug (To dispay EDD details after submitting)

src/main/java/org/recap/RecapConstants.java, src/main/java/org/recap/controller/RequestController.java, src/main/java/org/recap/repository/jpa/CustomerCodeDetailsRepository.java, src/main/java/org/recap/repository/jpa/RequestStatusDetailsRepository.java, src/main/java/org/recap/repository/jpa/RequestTypeDetailsRepository.java, src/main/java/org/recap/service/RequestService.java, src/main/resources/static/js/request.js, src/main/resources/templates/request.html, src/test/java/org/recap/controller/RequestControllerUT.java, src/test/java/org/recap/service/RequestServiceUT.java
Recap-737,724,718 Fixed long note Issues and Populate Request Type based on Item CC
=> Recap-737,724,718 Fixed long note Issues and Populate Request Type based on Item CC

src/main/resources/application.properties
RECAP-703 : Added application.properties.
=> RECAP-703 : Added application.properties.

src/main/java/org/recap/controller/RequestController.java, src/main/java/org/recap/model/search/RequestForm.java, src/test/java/org/recap/controller/RequestControllerUT.java, src/test/java/org/recap/model/search/RequestFormUT.java
Recap 737 - Change Volume Number Type From Integer To String.
=> Recap 737 - Change Volume Number Type From Integer To String.

src/main/java/org/recap/Main.java, src/main/java/org/recap/controller/RequestController.java, src/main/java/org/recap/controller/ScheduleJobsController.java, src/main/java/org/recap/controller/SearchRecordsController.java, src/main/java/org/recap/util/CollectionServiceUtil.java, src/main/java/org/recap/util/ReportsServiceUtil.java, src/main/java/org/recap/util/SearchUtil.java, src/main/java/org/recap/util/UserAuthUtil.java, src/main/resources/application-dev.properties, src/main/resources/application-junit.properties, src/main/resources/application-local-container.properties, src/main/resources/application-local.properties, src/main/resources/application-tst.properties, src/main/resources/application-uat.properties, src/main/resources/application.properties, src/test/java/org/recap/controller/CollectionControllerUT.java, src/test/java/org/recap/controller/RequestControllerUT.java, src/test/java/org/recap/controller/ScheduleJobsControllerUT.java, src/test/java/org/recap/util/CollectionServiceUtilUT.java
RECAP-773 : Removed the server.protocol from the properties.
=> RECAP-773 : Removed the server.protocol from the properties.

src/main/java/org/recap/service/RequestService.java, src/main/resources/static/js/request.js, src/main/resources/templates/request.html
Recap-777 Fixed bug for refreshing notes automatically with cancel button issue.
=> Recap-777 Fixed bug for refreshing notes automatically with cancel button issue.

src/main/java/org/recap/RecapConstants.java, src/main/java/org/recap/repository/jpa/RequestStatusDetailsRepository.java, src/main/java/org/recap/service/RequestService.java, src/main/resources/static/js/request.js, src/main/resources/templates/request.html
Recap-765 - Added code for  refreshing pending status.
=> Recap-765 - Added code for  refreshing pending status.

src/main/java/org/recap/controller/LoginController.java, src/main/java/org/recap/security/CASPropertyProvider.java, src/main/java/org/recap/security/MultiCASAndOAuthSecurityConfiguration.java, src/main/java/org/recap/security/ReCAPAbstractCasProtocolUrlBasedTicketValidator.java, src/main/java/org/recap/security/ReCAPCas20ServiceTicketValidator.java, src/main/java/org/recap/security/ReCAPExceptionTranslationFilter.java, src/main/java/org/recap/security/ReCAPSimpleUrlLogoutSuccessHandler.java, src/main/java/org/recap/security/UserManagementService.java, src/main/java/org/recap/service/CustomUserDetailsService.java, src/main/java/org/recap/spring/ApplicationContextProvider.java, src/main/java/org/recap/spring/PropertyValueProvider.java, src/main/java/org/recap/util/HelperUtil.java, src/main/java/org/recap/util/UserAuthUtil.java, src/main/java/org/springframework/security/cas/authentication/CasAuthenticationProvider.java
=> RECAP-798 : Added java doc.

src/main/java/org/recap/RecapConstants.java, src/main/java/org/recap/controller/RequestController.java, src/main/java/org/recap/controller/ScheduleJobsController.java, src/main/java/org/recap/service/RestHeaderService.java, src/main/java/org/recap/spring/SwaggerAPIProvider.java, src/main/java/org/recap/util/CollectionServiceUtil.java, src/main/java/org/recap/util/ReportsServiceUtil.java, src/main/java/org/recap/util/SearchUtil.java, src/main/java/org/recap/util/UserAuthUtil.java, src/main/resources/application.properties, src/test/java/org/recap/controller/RequestControllerUT.java, src/test/java/org/recap/service/RestHeaderServiceUT.java, src/test/java/org/recap/util/CollectionServiceUtilUT.java
Recap-867 Removed Hard coded swagger api keys
=> Recap-867 Removed Hard coded swagger api keys

src/main/java/org/recap/Main.java
=> Corrected method name.

src/main/java/org/recap/RecapConstants.java, src/main/java/org/recap/security/SessionFilter.java
RECAP-818 and MS-13: Fixed the issue with session time out
=> RECAP-818 and MS-13: Fixed the issue with session time out

src/main/resources/application.properties, src/main/resources/static/js/login.js, src/main/resources/templates/login.html
MS - 36 Email configuration for partners from login page.
=> MS - 36 Email configuration for partners from login page.

src/main/resources/application.properties, src/main/resources/templates/login.html
MS-69 HTC Tagline at the bottom of the page
=> MS-69 HTC Tagline at the bottom of the page

src/main/resources/templates/reports.html
Ms-136 - changed request report notes .
=> Ms-136 - changed request report notes .

src/main/resources/templates/request.html
Renamed Cancel text in button to Cancel Note.
=> MS-48 Change action of Cancel Request button.

src/main/java/org/recap/controller/RequestController.java, src/main/java/org/recap/model/search/BibDataField.java, src/main/java/org/recap/model/search/SearchResultRow.java, src/main/java/org/recap/util/MarcRecordViewUtil.java, src/main/resources/templates/request.html
MS-214 - To display marc fields in sorted order
MS-217 - To display last updated date as an extra column in Request Search UI
=> MS-214 and MS-217

src/main/java/org/recap/controller/RequestController.java, src/main/resources/static/js/request.js
MS-230 & MS-232 Fixed bugs in Create Request UI.
=> MS-230 & MS-232 Fixed bugs in Create Request UI.

src/main/resources/static/js/bulkRequest.js
MS-242 Help link for Bulk Request
=> MS-242 Help link for Bulk Request

src/main/java/org/recap/RecapConstants.java, src/main/java/org/recap/model/jpa/RequestItemEntity.java, src/main/java/org/recap/repository/jpa/RequestItemDetailsRepository.java, src/main/java/org/recap/util/RequestServiceUtil.java
MS-288 To display Request with the Scenario as item available in SCSB and GFA status 'Sch on REFILE WO:'
=> MS-288 To display Request with the Scenario as item available in SCSB and GFA status 'Sch on REFILE WO:'

src/main/java/org/recap/repository/jpa/RequestItemDetailsRepository.java, src/main/resources/static/js/request.js, src/main/resources/templates/request.html
Code changes for Cancel button enhancement and code fix for Request Search to display EDD request in Active Status
=> Code changes for Cancel button enhancement and code fix for Request Search to display EDD request in Active Status

src/main/resources/templates/request.html
Cancel Button enhancement - removed capitalization in the Popup box message.
=> Cancel Button enhancement - removed capitalization in the Popup box message.

src/main/java/org/recap/repository/jpa/RequestItemDetailsRepository.java
MS-316 Added code fix for Request Search bug
=> MS-316 Added code fix for Request Search bug

src/main/resources/templates/request.html
After placing a request , the formatting of the “click here” link  has been changed to Bold and underlined with a slightly larger font.
=> MS-352 Request options

src/main/resources/templates/request.html
MS-352 Request options changes
=> MS-352 Request options changes
